#!/usr/bin/env bash

# Define the path to the Nginx configuration file
nginx_conf="/etc/nginx/sites-enabled/default"
nginx_root="/var/www/html"
custom_error_page="/var/www/html/404.html"
output_string="Ceci n'est pas une page"

# Custom error page HTML file with the desired message
#echo -e "Ceci n'est pas une page \n" > /var/www/html/404.html

# Check if the custom error page exists
#if [ ! -f "$custom_error_page" ]; then
#    exit 1
#fi

#change ownership to current user
sudo chown -R "$USER:$USER" /var/www/html
sudo chmod -R 755 /var/www/
#echo "Hello World!" > /var/www/html/index.html
nginx_conf="/etc/nginx/sites-enabled/default"

#add custom header to config
sudo sed -i '/server_name _;/a\\tadd_header X-Served-By $HOSTNAME;' "$nginx"


# Define the redirection rule
#redirect_path="/redirect_me/"
#uri="https://www.youtube.com/watch?v=QH2-TGUlwu4"

#sudo sed -i "48i \ \ \ \ location $redirect_path {\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ return 301 $uri;\n \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ }" $nginx_conf



# Add the error_page directive within the server block
sudo sed -i '0,/try_files $uri $uri\/ =404;/s//&\n\t\terror_page 404 \/404.html;/' "$nginx_conf"


sudo nginx -t
#backup the default nginx page
#cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debain.bak

# If the configuration test is successful, reload Nginx to apply the changes
sudo systemctl reload nginx
