#!/usr/bin/env bash
# Terminating SSL on HAproxy” means that HAproxy is configured to handle encrypted traffic, unencrypt it and pass it on to its destination

sudo apt update
sudo apt install certbot python3-certbot-nginx
sudo certbot --nginx
#check the timer status - Time left until certificate expiration and renew
sudo systemctl status certbot.timer
#test renewal of certbot on expiration manual set-up
sudo certbot renew --dry-run


#IMPORTANT NOTES:
# - Congratulations! Your certificate and chain have been saved at:
#   /etc/letsencrypt/live/aceme.tech/fullchain.pem
#   Your key file has been saved at:
#   /etc/letsencrypt/live/aceme.tech/privkey.pem
#   Your cert will expire on 2024-10-09. To obtain a new or tweaked
#   version of this certificate in the future, simply run certbot again
#   with the "certonly" option. To non-interactively renew *all* of
#   your certificates, run "certbot renew"
# - If you like Certbot, please consider supporting our work by:
#
#   Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
#   Donating to EFF:                    https://eff.org/donate-le
